version: "3"
services:
  tofino_model:
    build: .
    scale: 2
    tty: true
    stdin_open: true
    privileged: true
    environment:
      - PLATFORM=barefoot-tofino-model
    volumes:
      - .:/workspace
    working_dir: /workspace
    entrypoint: ./stratum_tofino_entrypoint.sh
    stop_signal: SIGKILL
    ports:
      # Map ports to host (range)
      - 28000-28100:28000
    # TODO: the custom network does not seem to be needed?
    #networks:
    #  - stratum
networks:
  stratum:
    driver: bridge
